require("modules.autostart")
require("modules.binds")
require("modules.env")
require("modules.input")
require("modules.layout")
require("modules.looks")
require("modules.misc")
require("modules.plugins")
require("modules.windowrules")
pcall(require, "monitors")